**Sequential Feature Selection: Comes under Wrapper method for unsupervised Feature selectio/unsupervised data** 
Link:https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SequentialFeatureSelector.html#

In [1]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np


In [2]:
iris = load_iris()
X,y = load_iris(return_X_y=True)

In [3]:
type(X)

numpy.ndarray

In [4]:
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])
data1.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [5]:
knn = KNeighborsClassifier(n_neighbors=3)
sfs = SequentialFeatureSelector(knn, n_features_to_select=3)


In [6]:
sfs.fit(X,y=None)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 678, in _fit_and_score
    estimator.fit(X_train, **fit_params)
TypeError: fit() missing 1 required positional argument: 'y'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be s

SequentialFeatureSelector(estimator=KNeighborsClassifier(n_neighbors=3),
                          n_features_to_select=3)

In [7]:
#mn = sfs.get_support()
#op = sfs.transform(X)

In [8]:
#mn

In [9]:
#op

**Recursive Feature Elimination: Comes under Wrapper method for unsupervised Feature selectio/unsupervised data** 

In [10]:
from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

In [12]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, n_features_to_select=5, step=1)
selector = selector.fit(X)
selector.support_
selector.ranking_

TypeError: ignored

**Feature selector that removes all low-variance features**. This feature selection algorithm looks only at the features (X), not the desired outputs (y), and can thus be used for unsupervised learning.

In [13]:
from sklearn.feature_selection import VarianceThreshold
X = [[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]]
selector = VarianceThreshold()
selector.fit_transform(X)

array([[2, 0],
       [1, 4],
       [1, 1]])

As an example, suppose that we have a dataset with boolean features, and we want to remove all features that are either one or zero (on or off) in more than 80% of the samples. Boolean features are Bernoulli random variables, and the variance of such variables is given by using the threshold .8 * (1 - .8).
As expected, VarianceThreshold has removed the first column, which has a probability  p= 5/6>0.8 of containing a zero.
link: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html

In [14]:
from sklearn.feature_selection import VarianceThreshold
X = [[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 1, 1], [0, 1, 0], [0, 1, 1]]
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(X)

array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

The feature ranking, such that ranking_[i] corresponds to the ranking position of the i-th feature. Selected (i.e., estimated best) features are assigned rank 1

# **Installing scikit-feature which is a is an open-source feature selection repository in Python developed at Arizona State University.**
Link: https://jundongl.github.io/scikit-feature/ 

In [ ]:
pip install skfeature-chappers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.3/66.3 KB 9.9 MB/s eta 0:00:00


In [ ]:
!pip install git+https://github.com/jundongl/scikit-feature.git
#https://github.com/jundongl/scikit-feature.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/jundongl/scikit-feature.git to /tmp/pip-req-build-p3vv70u1
  Running command git clone --filter=blob:none --quiet https://github.com/jundongl/scikit-feature.git /tmp/pip-req-build-p3vv70u1
  Resolved https://github.com/jundongl/scikit-feature.git to commit 48cffad4e88ff4b9d2f1c7baffb314d1b3303792
  Preparing metadata (setup.py) ... done
  Created wheel for skfeature: filename=skfeature-1.0.0-py3-none-any.whl size=61509 sha256=3278810bf02f8acbc5f098972a91ca3ba1b934e8d7ed164e2e2de793c6eac019
  Stored in directory: /tmp/pip-ephem-wheel-cache-_0fe7xqf/wheels/ea/ca/0b/ea331396461510ff572967528a880848ef75cc192b2f6074eb
Successfully built skfeature


**Unsupervised feature selection using Laplacian Score. First, we construct affinity matrix which is required by Laplacian Score**

In [ ]:
import scipy.io
from sklearn.metrics import accuracy_score
#from sklearn import cross_validation
from sklearn.model_selection import train_test_split
from sklearn import svm
from skfeature.function.statistical_based import f_score
from skfeature.function.similarity_based import lap_score


In [ ]:
from skfeature.utility import construct_W
kwargs_W = {"metric":"euclidean","neighbor_mode":"knn","weight_mode":"heat_kernel","k":5,'t':1}
W = construct_W.construct_W(X, **kwargs_W)

In [ ]:
score = lap_score.lap_score(X, W=W)
score

array([0.41203983, 0.39954016, 0.40463193, 0.3812733 , 0.45851737,
       0.49236869, 0.53510396, 0.42886452, 0.42279366, 0.40481904])

In [ ]:
idx = lap_score.feature_ranking(score)
idx

array([3, 1, 2, 9, 0, 8, 7, 4, 5, 6])

In [ ]:
# Get the list of all column names from headers
column_headers = data1.columns.values.tolist()
print("The Column Header :", column_headers)

The Column Header : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'target']


In [ ]:
df2 = data1.iloc[0,[0,2,3]]
df2

sepal length (cm)    5.1
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [ ]:
num_fea = 3
selected_features = X[:, idx[0:num_fea]]
selected_features

array([[0.54488318, 0.71518937, 0.60276338],
       [0.92559664, 0.52889492, 0.56804456],
       [0.78052918, 0.79915856, 0.46147936],
       [0.56843395, 0.77423369, 0.45615033],
       [0.06022547, 0.43703195, 0.6976312 ],
       [0.10204481, 0.43860151, 0.98837384],
       [0.13818295, 0.11037514, 0.65632959],
       [0.60484552, 0.4686512 , 0.97676109],
       [0.69247212, 0.41426299, 0.0641475 ],
       [0.7163272 , 0.66741038, 0.13179786],
       [0.96218855, 0.27000797, 0.73519402],
       [0.29743695, 0.84640867, 0.69947928],
       [0.6439902 , 0.50132438, 0.95608363],
       [0.29828233, 0.4287687 , 0.13547406],
       [0.89192336, 0.36756187, 0.43586493],
       [0.61555956, 0.86812606, 0.16249293],
       [0.86638233, 0.45354268, 0.7220556 ],
       [0.01852179, 0.05433799, 0.19999652],
       [0.23789282, 0.6214784 , 0.57722859],
       [0.94437239, 0.20984375, 0.18619301],
       [0.17960368, 0.69634349, 0.37775184],
       [0.26332238, 0.21689698, 0.6630782 ],
       [0.

**sklearn.feature_selection.SelectKBest: Select features according to the k highest scores of scoring function (here Chi2).**
Link: https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest

In [21]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2
X, y = load_digits(return_X_y=True)
X.shape

X_new = SelectKBest(chi2, k=20).fit_transform(X)
X_new.shape

TypeError: ignored